Feature/conn shedding
reddit/reddit-service-websockets pull request #8
Opened 2017-02-14 16:33 UTC by ckwang8128

In order to support graceful websocket service shutdown, this adds
an endpoint behind basic auth for quiescing the service. A quiesced
service sheds existing connections and returns 410 responses for
all inbound requests. Health checks also return currrent state and return the number of existing connections:

```
{"status": "OK", "connections": 100}
...
# Quiesce
...
{"status": "quiesced", "connections": 100}
```

Design doc: 
https://docs.google.com/a/reddit.com/document/d/1N-bjMmAr2UWtSwRBepul76HJ6XtQWZxDt5pCLrLbmBA/edit?usp=sharing

I won't have time to get this out this week so tests are still coming, but I wanted some feedback on the main code. 

:eyeglasses: @dellis23 @spladug

2017-02-14 17:48 UTC, dellis23 commented on example.ini
> +web.admin_auth = aHVudGVyMg==
Will this be public facing?  Maybe we should pick a longer one.

Edit: Very funny.

2017-02-14 18:45 UTC, spladug requested changes
just a comment on the name of the function and to clean up salon until the tests etc. are in place. looks great, clever way of doing the delayed shedding.

2017-02-14 18:45 UTC, spladug commented on reddit_service_websockets/socketserver.py
> +        self.connections = set()
why a set instead of just a list?

2017-02-14 18:45 UTC, spladug commented on reddit_service_websockets/socketserver.py
> +    def _authorized(self, environ, admin_auth):
perhaps `_authorized_to_quiesce` or something?

2017-02-14 18:48 UTC, ckwang8128 commented on example.ini
> +web.admin_auth = aHVudGVyMg==
:trollface: 

The endpoint will be public-facing, we'll be populating this field in production via an internal generated password in Puppet.

2017-02-14 18:50 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +        self.connections = set()
List probably works better here actually; I think I initially chose to use set anticipating some stuff around checking connection existence in the set but things ended up being simpler. Updating!

2017-02-14 18:50 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +    def _authorized(self, environ, admin_auth):
👍

2017-02-14 19:38 UTC, dellis23 commented on reddit_service_websockets/socketserver.py
> +        if path_info == '/quiesce':
Do we wanna make this a POST request?

2017-02-14 19:47 UTC, dellis23 commented on reddit_service_websockets/socketserver.py
> +            self.quiesced = True
Do you want to set this before popping off connections so new ones can't be accepted in the time where this loop is running?

2017-02-14 20:29 UTC, dellis23 commented
💅 Small questions

2017-02-14 20:30 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +            self.quiesced = True
oh good call, I need to move the flag flipping and check before I make a copy of the connections.

2017-02-23 22:56 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +        if path_info == '/quiesce':
I think that actually makes sense here since we're changing state with the first request.

2017-02-23 23:24 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +        self.connections = set()
Ah. I just realized -> I chose set for faster removal of websocket connections in the event that connections are terminated by standard disconnecting behavior.

2017-02-24 18:02 UTC, ckwang8128 commented
:haircut: Added tests, addressed questions. Thanks for initial feedback!

2017-02-24 18:03 UTC, dellis23 commented
🐟 cool!

2017-02-24 18:04 UTC, ckwang8128 commented on reddit_service_websockets/socketserver.py
> +        self.connections = set()
See https://github.com/reddit/reddit-service-websockets/pull/8/files/9c1ef3962e6a1425abc7e4cfb1fb614cae8849f2#diff-72d24bea125850462951b12d9b42ce47R187

2017-02-24 19:06 UTC, spladug approved these changes

2017-02-27 19:40 UTC, merged